### ISSUE TITLE
Customising forms with html elements

### ISSUE THREAD

**Issue by Danwhy** [dwyl/autoform#15]
The current iteration of autoform takes a schema and renders a form based on it. If we want to customise that form, our current options are excluding fields from being rendered.

This does provide us with some amount of flexibility around how the form looks, and we can abuse this to fully customise a form such that we can put different fields in different places, interspersed with custom html elements, or combine multiple schemas into one form, which we can then submit using javascript.

However, this abuse leads to non-standard html which is completely inaccessible. It would be much better if we could pass a list of schemas, fields and html elements to our function in order to render exactly what we want in a single accessible html form which can be used with or without js.

My proposed solution for this currently is to define a function which takes a list of either:

- Schemas, by default rendering all fields, but being able to specify `only` or `exclude`

or

- HTML elements. I'd need to look into how we'd accept these as arguments, whether it would need to be strings or something else

or a combination of the two.

We could then render all of these in one form, posting to a given endpoint.

Any opinions on this suggestion?

**Comment by Cleop** [comment]
@Danwhy - I believe it is now in place to be able to put HTML between versions of the form. Is it possible to put html between a label and an input, to have the line of text before the input field in this example?
![image](https://user-images.githubusercontent.com/16775804/52043111-bf552200-2536-11e9-8b19-5d7d3df7d157.png)

**Comment by Danwhy** [comment]
It is, but only if we exclude that field from being autogenerated, and instead pass it in manually as html.

**Comment by Cleop** [comment]
Closing this issue as functionality now complete
