### ISSUE TITLE
Give users option to put label before or after input

### ISSUE THREAD

**Issue by RobStallion** [dwyl/autoform#20]
Currently when you call the `render_autoform` function it creates a `<label>` followed by the input type needed, e.g. text, checkbox.

![image](https://user-images.githubusercontent.com/15571853/47181104-10d7f900-d31a-11e8-8cb8-c1fffca22ad6.png)
This works well but does not provide much flexibility to the users.

It would be good if we allowed users to customise this with parameters that they pass into the function. We should be able to achieve this if we pass in a key (something like `input_first:`) followed by a list of the column names where we would like to display the input first, to the functions opts.

**Comment by nelsonic** [comment]
@RobStallion now that you have implemented `input_first`, consider showing a _visual_ example of the effect in the readme/docs. 😉

**Comment by RobStallion** [comment]
Ahhhh @nelsonic Good point. I'll get that in there soon as 👍
