### ISSUE TITLE
Error when using a schema made up of two words

### ISSUE THREAD

**Issue by Cleop** [dwyl/autoform#36]
![image](https://user-images.githubusercontent.com/16775804/50011558-58929e00-ffb4-11e8-8e29-e895a196f9ff.png)

My schema is called StaticPage and its path should be `static_page_path` however autoform is not inserting the underscore for me, hence the error.

**Comment by SimonLab** [comment]
The `schema_name` function needs to be updated to also use `Macro.underscore`:
https://github.com/dwyl/autoform/blob/24762a1bc82dd1fbfc57f1802b2e30401f93a83a/lib/autoform.ex#L281

**Comment by SimonLab** [comment]
using `Macro.underscore` in the wrong order in #40 
needs to be `schema |> to_string() |> String.split(".") |> List.last() |> Macro.underscore()`
as the `underscore` function will convert dots to "/", so the `split(".")` function needs to be run first
![image](https://user-images.githubusercontent.com/6057298/50374225-bb9eb900-05e2-11e9-99a8-566ec100f07f.png)

**Comment by Cleop** [comment]
This issue has now been resolved.
