### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by Danwhy** [dwyl/autoform#5]
We need to set up a CI for this so we can ensure all tests are passing, and to run an accessibility checker on an example implementation of the autoform generator.

- [x] Set up CI
  - [x] Run tests
  - [x] Run accessibility checker

**Comment by Danwhy** [comment]
Set up and running tests and accessibility check:
<img width="812" alt="screen shot 2018-10-01 at 16 45 20" src="https://user-images.githubusercontent.com/8939909/46299466-4e5a2980-c599-11e8-848b-8e5df272b394.png">

**Comment by nelsonic** [comment]
Thanks Dan! ❤️ ✅
